name: Dev Environment — Terraform

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  terraform_plan:
    name: Plan (Dev)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    uses: alberto7088/workflows/.github/workflows/terraform-deployment.yaml@main
    with:
      environment:        dev
      terraform-action:   plan
      terraform-directory: infra/terraform
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_DEV }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET_DEV }}
      GCP_PROJECT:     ${{ secrets.GCP_PROJECT_DEV }}

  terraform_apply:
    name: Apply (Dev)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    uses: alberto7088/workflows/.github/workflows/terraform-deployment.yaml@main
    with:
      environment:        dev
      terraform-action:   apply
      terraform-directory: infra/terraform
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_DEV }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET_DEV }}
      GCP_PROJECT:     ${{ secrets.GCP_PROJECT_DEV }}
